### ISSUE TITLE
OpenCV interoperability

### ISSUE THREAD

**Issue by kahrabji08** [arrayfire/arrayfire#1486]
Hi,
Am trying to use these functions [https://github.com/arrayfire-community/arrayfire_opencv](url) in order to incorporate array fire to my previous OpenCV projects. Is these functions valid? because when I tried to include it to my project I got this error:

/home/mohamed/Hassan/arrayfire/arrayfire-project-templates/test/src/af_cv.hpp:39:22: fatal error: af/utils.h: No such file or directory
 `#include <af/utils.h>`
                      ^
compilation terminated.
make[2]: *** [src/CMakeFiles/FOO_CORE.dir/orb_matching.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/FOO_CORE.dir/all] Error 2
make: *** [all] Error 2

When I tried to comment it or use `#include <af/util.h>` instead, I got more errors:
![image](https://cloud.githubusercontent.com/assets/16088425/16719872/4b68a83a-4762-11e6-959b-46172de148dc.png)

**Comment by pavanky** [comment]
@kahrabji08 That repo uses an older version of arrayfire.

@syurkevi is working on adding this support for v3.4.0
please follow https://github.com/arrayfire/arrayfire/issues/529 for future updates.
