### ISSUE TITLE
Build error on OSX 10.11

### ISSUE THREAD

**Issue by dpo** [arrayfire/arrayfire#1213]
Sorry to bother, but I've got another build error, on OSX 10.11 this time. I'm using the 3.2.2 tag and version af3.2.2 of Forge. The error I'm getting is:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/CSCommon.h:200:32: error: enumerator value evaluates to -2147483648, which cannot be narrowed to type 'uint32_t' (aka 'unsigned int') [-Wc++11-narrowing]
    kSecCSConsiderExpiration = 1 << 31,         /* consider expired certificates invalid */
                               ^
```
Here's the [full log](http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/3886/version=el_capitan/consoleFull).

Thanks for any help!

**Comment by pavanky** [comment]
@dpo Can you post the log to a gist and link it here?

**Comment by dpo** [comment]
@pavanky Sorry for the slow reply. I don't have direct access to a 10.11 machine, only through Travis and the brew bot, but `arrayfire` now compiles correctly on all of 10.9, 10.10 and 10.11. There might have been an OS update in the interim. So it looks all good. Thanks for the assistance!
