### ISSUE TITLE
CUDA backend does not build with Boost 1.60

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1210]
Apparently something in this combination requires setting `-std=c++11`. This needs fixing.

https://svn.boost.org/trac/boost/ticket/11852

**Comment by pavanky** [comment]
Compiling with `-std=c++11` with gcc 5.3.0 and CUDA 7.5 results in the following:
```
-- Generating /home/pavan/Work/arrayfire/build/src/backend/cuda/CMakeFiles/afcuda.dir/kernel/./afcuda_generated_convolve_separable.cu.o
/opt/cuda/bin/nvcc /home/pavan/Work/arrayfire/src/backend/cuda/kernel/convolve_separable.cu -c -o /home/pavan/Work/arrayfire/build/src/backend/cuda/CMakeFiles/afcuda.dir/kernel/./afcuda_generated_convolve_separable.cu.o -ccbin /usr/bin/cc -m64 -DWITH_FREEIMAGE -DGLEW_MX -DWITH_GRAPHICS -DOS_LNX -DAF_CUDA -DWITH_CUDA_LINEAR_ALGEBRA -Dafcuda_EXPORTS -Xcompiler ,\"-fPIC\",\"-O0\",\"-DNDEBUG\" -std=c++11 -Xcompiler -fvisibility=hidden -gencode arch=compute_30,code=sm_30 -gencode arch=compute_30,code=sm_30 -DNVCC -I/opt/cuda/include -I/usr/include -I/home/pavan/Work/arrayfire/build/third_party/forge/include -I/home/pavan/Work/arrayfire/src -I/home/pavan/Work/arrayfire/include -I/home/pavan/Work/arrayfire/src/backend -I/home/pavan/Work/arrayfire/src/api/c -I/opt/cuda/include -I/home/pavan/Work/arrayfire/src/backend/cuda -I/home/pavan/Work/arrayfire/build/src/backend/cuda -I/opt/cuda/nvvm/include
```

Compile error:

```
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined
```

**Comment by pavanky** [comment]
Well the simplest fix seems to be to use `__STRICT_ANSI__` for boost 1.60.

@umar456 do you mind if I force this for all versions ? This only seems to affect custom, compiler defined, data types anyway.

**Comment by eyalroz** [comment]
@pavanky  Where exactly would I add this this macro?

**Comment by 9prady9** [comment]
@eyalroz Please see the changes in [this](https://github.com/arrayfire/arrayfire/pull/1211) PR. If you are using CMake for your project, it will be similar change in our project cmake build files. The change is essentially passing on the right symbol for nvcc compiler.

**Comment by dillerch** [comment]
Do you know what is causing this compiler error? I am working on a different project which does not use this library or boost at all and adding __STRICT_ANSI__ does not seem to help.

**Comment by pavanky** [comment]
@dillerch boost 1.6 added support for `__float128` where as `nvcc` did not. This was causing the issue. Considering that `__float128` is a gcc only extension, it can be disabled by using `__STRICT_ANSI__`. I am not sure what error you are seeing or if this will help.

**Comment by eyalroz** [comment]
Well, I did try adding this macro, but it didn't help; on the contrary, I get _more_ error messages with it... plus - I'm not using Boost 1.60, but rather Fedora 22's Boost 1.58.

**Comment by pavanky** [comment]
@eyalroz Where are you seeing this error ?
