### PR TITLE
CMake fixes for Xcode generator

### LINKED ISSUE #1492: XCode link error regarding forge library file non-existent
When building the latest devel branch on OS X 10.11 with XCode, I get the following linker error. Note that the library is in the `Release` subdirectory rather at `/Users/as12312/Software/ArrayFire/Xcode/third_party/forge/src/forge-ext-build/src/Release/`.

```
Ld Xcode/src/backend/opencl/Release/libafopencl.3.4.0.dylib normal x86_64
    cd /Users/as12312/Software/ArrayFire
    export MACOSX_DEPLOYMENT_TARGET=10.11
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -L/Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/Release -F/Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/Release -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks -filelist /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/afopencl.build/Objects-normal/x86_64/afopencl.3.4.0.LinkFileList -install_name /libafopencl.3.4.0.dylib -mmacosx-version-min=10.11 -dynamiclib -Wl,-headerpad_max_install_names -install_name @rpath/libafopencl.3.dylib /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/opencl_sort_by_key_float.build/Objects-normal/x86_64/sort_by_key_impl.o /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/opencl_sort_by_key_double.build/Objects-normal/x86_64/sort_by_key_impl.o /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/opencl_sort_by_key_int.build/Objects-normal/x86_64/sort_by_key_impl.o /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/opencl_sort_by_key_uint.build/Objects-normal/x86_64/sort_by_key_impl.o /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/opencl_sort_by_key_intl.build/Objects-normal/x86_64/sort_by_key_impl.o /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/opencl_sort_by_key_uintl.build/Objects-normal/x86_64/sort_by_key_impl.o /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/opencl_sort_by_key_short.build/Objects-normal/x86_64/sort_by_key_impl.o /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/opencl_sort_by_key_ushort.build/Objects-normal/x86_64/sort_by_key_impl.o /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/opencl_sort_by_key_char.build/Objects-normal/x86_64/sort_by_key_impl.o /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/opencl_sort_by_key_uchar.build/Objects-normal/x86_64/sort_by_key_impl.o /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/opencl_scan_by_key_af_add_t.build/Objects-normal/x86_64/scan_by_key_impl.o /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/opencl_scan_by_key_af_mul_t.build/Objects-normal/x86_64/scan_by_key_impl.o /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/opencl_scan_by_key_af_max_t.build/Objects-normal/x86_64/scan_by_key_impl.o /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/opencl_scan_by_key_af_min_t.build/Objects-normal/x86_64/scan_by_key_impl.o -framework OpenCL /Users/as12312/Software/ArrayFire/Xcode/third_party/clBLAS/lib/import/libclBLAS.a /Users/as12312/Software/ArrayFire/Xcode/third_party/clFFT/lib/import/libclFFT.a -framework Accelerate -framework Accelerate -framework Accelerate /usr/local/lib/libfreeimage.dylib /Users/as12312/Software/ArrayFire/Xcode/third_party/forge/src/forge-ext-build/src/libforge.dylib /usr/local/lib/libGLEWmx.dylib -framework OpenGL -framework OpenGL -single_module -compatibility_version 3.0.0 -current_version 3.4.0 -Xlinker -dependency_info -Xlinker /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/ARRAYFIRE.build/Release/afopencl.build/Objects-normal/x86_64/afopencl.3.4.0_dependency_info.dat -o /Users/as12312/Software/ArrayFire/Xcode/src/backend/opencl/Release/libafopencl.3.4.0.dylib

clang: error: no such file or directory: '/Users/as12312/Software/ArrayFire/Xcode/third_party/forge/src/forge-ext-build/src/libforge.dylib'
```

### LINKED ISSUE #1494: 'Expected expression' error in opencl tests due to undefined TEST_DIR
When building with `BUILD_TEST` option `ON` in Xcode, I get multiple `Expected expression` errors in lines which use the `TEST_DIR` macro. Detailed error message for `moments_opencl`, and similar errors for `harris_opencl`:

```
CompileC Xcode/test/ARRAYFIRE.build/Release/moments_opencl.build/Objects-normal/x86_64/moments.o test/moments.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/as12312/Software/ArrayFire
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O3 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DCMAKE_INTDIR=\"Release\" -DWITH_FREEIMAGE -DGLEW_MX -DWITH_GRAPHICS -DOS_MAC -DAF_UNIFIED -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -mmacosx-version-min=10.11 -Wno-sign-conversion -I/Users/as12312/Software/ArrayFire/Xcode/test/Release/include -I/usr/local/include -I/Users/as12312/Software/ArrayFire/Xcode/third_party/forge/include -I/usr/X11R6/include -I/Users/as12312/Software/ArrayFire/include -I/Users/as12312/Software/ArrayFire/src/backend -I/Users/as12312/Software/ArrayFire/src/api/c -I/Users/as12312/Software/ArrayFire/test/../test/gtest/include -I/Users/as12312/Software/ArrayFire/test -I/Users/as12312/Software/ArrayFire/Xcode/test/ARRAYFIRE.build/Release/moments_opencl.build/DerivedSources/x86_64 -I/Users/as12312/Software/ArrayFire/Xcode/test/ARRAYFIRE.build/Release/moments_opencl.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/as12312/Software/ArrayFire/Xcode/test/Release -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks -DNDEBUG -DAF_OPENCL -Wall -fvisibility=hidden -D TEST_DIR=\\/Users/as12312/Software/ArrayFire/test/data\\ -MMD -MT dependencies -MF /Users/as12312/Software/ArrayFire/Xcode/test/ARRAYFIRE.build/Release/moments_opencl.build/Objects-normal/x86_64/moments.d --serialize-diagnostics /Users/as12312/Software/ArrayFire/Xcode/test/ARRAYFIRE.build/Release/moments_opencl.build/Objects-normal/x86_64/moments.dia -c /Users/as12312/Software/ArrayFire/test/moments.cpp -o /Users/as12312/Software/ArrayFire/Xcode/test/ARRAYFIRE.build/Release/moments_opencl.build/Objects-normal/x86_64/moments.o

/Users/as12312/Software/ArrayFire/test/moments.cpp:145:31: error: expected expression
    momentsOnImageTest(string(TEST_DIR"/moments/gray_seq_16_moments.test"), string(TEST_DIR"/imageio/gray_seq_16.png"), false);
                              ^
In file included from <built-in>:337:
<command line>:9:18: note: expanded from here
#define TEST_DIR \/Users/as12312/Software/ArrayFire/test/data\\
                 ^
/Users/as12312/Software/ArrayFire/test/moments.cpp:145:84: error: expected expression
    momentsOnImageTest(string(TEST_DIR"/moments/gray_seq_16_moments.test"), string(TEST_DIR"/imageio/gray_seq_16.png"), false);
                                                                                   ^
In file included from <built-in>:337:
<command line>:9:18: note: expanded from here
#define TEST_DIR \/Users/as12312/Software/ArrayFire/test/data\\
                 ^
/Users/as12312/Software/ArrayFire/test/moments.cpp:150:31: error: expected expression
    momentsTest<float>(string(TEST_DIR"/moments/simple_mat_batch_moments.test"));
                              ^
In file included from <built-in>:337:
<command line>:9:18: note: expanded from here
#define TEST_DIR \/Users/as12312/Software/ArrayFire/test/data\\
                 ^
/Users/as12312/Software/ArrayFire/test/moments.cpp:155:31: error: expected expression
    momentsOnImageTest(string(TEST_DIR"/moments/color_seq_16_moments.test"), string(TEST_DIR"/imageio/color_seq_16.png"), true);
                              ^
In file included from <built-in>:337:
<command line>:9:18: note: expanded from here
#define TEST_DIR \/Users/as12312/Software/ArrayFire/test/data\\
                 ^
/Users/as12312/Software/ArrayFire/test/moments.cpp:155:85: error: expected expression
    momentsOnImageTest(string(TEST_DIR"/moments/color_seq_16_moments.test"), string(TEST_DIR"/imageio/color_seq_16.png"), true);
                                                                                    ^
In file included from <built-in>:337:
<command line>:9:18: note: expanded from here
#define TEST_DIR \/Users/as12312/Software/ArrayFire/test/data\\
                 ^
/Users/as12312/Software/ArrayFire/test/moments.cpp:160:35: error: expected expression
    momentsTest<TypeParam>(string(TEST_DIR"/moments/simple_mat_moments.test"));
                                  ^
In file included from <built-in>:337:
<command line>:9:18: note: expanded from here
#define TEST_DIR \/Users/as12312/Software/ArrayFire/test/data\\
                 ^
6 errors generated.
```

### PR DESCRIPTION
**Pull request by schuhschuh**
Disclaimer: Fixes the build issue with Xcode generator. Have not tested Makefile generator.
- [x] Test if non-IDE build still works.

* Closes #1492 - FIX: xforge-ext library file path when build with Xcode
* Closes #1494 - Fix escape character issues with Xcode generator.

### CODE REVIEW

**Comment by schuhschuh** [comment]
After these two changes and fix #1498 the Xcode build of all backends, examples, and tests is successful.

**Comment by schuhschuh** [comment]
Build with Makefile generator on OS X 10.11 successful as well.
