### ISSUE TITLE
Compilation error on cudaStreamCaptureMode with cuda 10.2

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2711]
Hum, I got a strange compilation error with cuda 10.2 on gcc 6.1 (Ubuntu16):

In file included from /usr/local/cuda-10.2/include/channel_descriptor.h:61:0,
                 from /usr/local/cuda-10.2/include/cuda_runtime.h:95,
                 from /home/wtambellini/repos/arrayfire/src/backend/cuda/platform.hpp:13,
                 from /home/wtambellini/repos/arrayfire/src/backend/cuda/cublas.cpp:12:
/usr/local/cuda-10.2/include/cuda_runtime_api.h:2532:88: error: use of enum ‘cudaStreamCaptureMode’ without previous declaration
 extern __host__ cudaError_t CUDARTAPI cudaStreamBeginCapture(cudaStream_t stream, enum cudaStreamCaptureMode mode);

It compiles correctly with cuda 10.0.
TBC

**Comment by WilliamTambellini** [comment]
A similar issue:
https://webcache.googleusercontent.com/search?q=cache:0U61o-m6XvcJ:https://devtalk.nvidia.com/default/topic/1064351/tensorrt/compilation-error-for-tensorrt-samples/+&cd=2&hl=en&ct=clnk&gl=us&client=ubuntu

**Comment by WilliamTambellini** [comment]
cmake was mixing cuda 10.0 and 10.2. 
rm CMakeCache.txt.
