### ISSUE TITLE
FTBFS: error: reference to ‘array’ is ambiguous

### ISSUE THREAD

**Issue by ghisvail** [arrayfire/arrayfire#1585]
Tried to compile the latest tip of `devel` (2f474a804a381915770981f518493204bb53d3c1) on Debian, but getting a `error: reference to ‘array’ is ambiguous` in `test/clamp.cpp`. Sounds like someone perhaps brought `std::array` to the `af` namespace, hence the ambiguity?

Detailed error:
```
[ 70%] Building CXX object test/CMakeFiles/clamp_opencl.dir/clamp.cpp.o
/home/gvaillan/local/src/arrayfire/test/clamp.cpp: In member function ‘virtual void ClampTests_FloatArrayArray_Test::TestBody()’:
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:24:5: error: reference to ‘array’ is ambiguous
     array in = af::randu(num, f32);
     ^~~~~
In file included from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:11:0:
/home/gvaillan/local/src/arrayfire/include/af/array.h:27:17: note: candidates are: class af::array
     class AFAPI array {
                 ^~~~~
In file included from /usr/include/c++/6/tuple:39:0,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-port.h:708,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-internal.h:40,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/gtest.h:58,
                 from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:10:
/usr/include/c++/6/array:90:12: note:                 template<class _Tp, long unsigned int _Nm> struct std::array
     struct array
            ^~~~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:25:5: error: reference to ‘array’ is ambiguous
     array lo = af::randu(num, f32)/10;       // Ensure lo <= 0.1
     ^~~~~
In file included from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:11:0:
/home/gvaillan/local/src/arrayfire/include/af/array.h:27:17: note: candidates are: class af::array
     class AFAPI array {
                 ^~~~~
In file included from /usr/include/c++/6/tuple:39:0,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-port.h:708,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-internal.h:40,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/gtest.h:58,
                 from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:10:
/usr/include/c++/6/array:90:12: note:                 template<class _Tp, long unsigned int _Nm> struct std::array
     struct array
            ^~~~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:26:5: error: reference to ‘array’ is ambiguous
     array hi = 1.0 - af::randu(num, f32)/10; // Ensure hi >= 0.9
     ^~~~~
In file included from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:11:0:
/home/gvaillan/local/src/arrayfire/include/af/array.h:27:17: note: candidates are: class af::array
     class AFAPI array {
                 ^~~~~
In file included from /usr/include/c++/6/tuple:39:0,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-port.h:708,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-internal.h:40,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/gtest.h:58,
                 from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:10:
/usr/include/c++/6/array:90:12: note:                 template<class _Tp, long unsigned int _Nm> struct std::array
     struct array
            ^~~~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:27:14: error: ‘lo’ was not declared in this scope
     af::eval(lo, hi);
              ^~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:27:18: error: ‘hi’ was not declared in this scope
     af::eval(lo, hi);
                  ^~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:31:5: error: reference to ‘array’ is ambiguous
     array out = clamp(in, lo, hi);
     ^~~~~
In file included from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:11:0:
/home/gvaillan/local/src/arrayfire/include/af/array.h:27:17: note: candidates are: class af::array
     class AFAPI array {
                 ^~~~~
In file included from /usr/include/c++/6/tuple:39:0,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-port.h:708,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-internal.h:40,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/gtest.h:58,
                 from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:10:
/usr/include/c++/6/array:90:12: note:                 template<class _Tp, long unsigned int _Nm> struct std::array
     struct array
            ^~~~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:32:5: error: ‘out’ was not declared in this scope
     out.host(&hout[0]);
     ^~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:33:5: error: ‘in’ was not declared in this scope
     in.host(&hin[0]);
     ^~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp: In member function ‘virtual void ClampTests_FloatArrayScalar_Test::TestBody()’:
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:46:5: error: reference to ‘array’ is ambiguous
     array in = af::randu(num, f32);
     ^~~~~
In file included from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:11:0:
/home/gvaillan/local/src/arrayfire/include/af/array.h:27:17: note: candidates are: class af::array
     class AFAPI array {
                 ^~~~~
In file included from /usr/include/c++/6/tuple:39:0,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-port.h:708,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-internal.h:40,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/gtest.h:58,
                 from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:10:
/usr/include/c++/6/array:90:12: note:                 template<class _Tp, long unsigned int _Nm> struct std::array
     struct array
            ^~~~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:47:5: error: reference to ‘array’ is ambiguous
     array lo = af::randu(num, f32)/10; // Ensure lo <= 0.1
     ^~~~~
In file included from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:11:0:
/home/gvaillan/local/src/arrayfire/include/af/array.h:27:17: note: candidates are: class af::array
     class AFAPI array {
                 ^~~~~
In file included from /usr/include/c++/6/tuple:39:0,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-port.h:708,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-internal.h:40,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/gtest.h:58,
                 from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:10:
/usr/include/c++/6/array:90:12: note:                 template<class _Tp, long unsigned int _Nm> struct std::array
     struct array
            ^~~~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:51:5: error: reference to ‘array’ is ambiguous
     array out = clamp(in, lo, hi);
     ^~~~~
In file included from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:11:0:
/home/gvaillan/local/src/arrayfire/include/af/array.h:27:17: note: candidates are: class af::array
     class AFAPI array {
                 ^~~~~
In file included from /usr/include/c++/6/tuple:39:0,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-port.h:708,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-internal.h:40,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/gtest.h:58,
                 from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:10:
/usr/include/c++/6/array:90:12: note:                 template<class _Tp, long unsigned int _Nm> struct std::array
     struct array
            ^~~~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:53:5: error: ‘out’ was not declared in this scope
     out.host(&hout[0]);
     ^~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:54:5: error: ‘in’ was not declared in this scope
     in.host(&hin[0]);
     ^~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:55:5: error: ‘lo’ was not declared in this scope
     lo.host(&hlo[0]);
     ^~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp: In member function ‘virtual void ClampTests_FloatScalarArray_Test::TestBody()’:
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:66:5: error: reference to ‘array’ is ambiguous
     array in = af::randu(num, f32);
     ^~~~~
In file included from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:11:0:
/home/gvaillan/local/src/arrayfire/include/af/array.h:27:17: note: candidates are: class af::array
     class AFAPI array {
                 ^~~~~
In file included from /usr/include/c++/6/tuple:39:0,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-port.h:708,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-internal.h:40,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/gtest.h:58,
                 from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:10:
/usr/include/c++/6/array:90:12: note:                 template<class _Tp, long unsigned int _Nm> struct std::array
     struct array
            ^~~~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:68:5: error: reference to ‘array’ is ambiguous
     array hi = 1.0 - af::randu(num, f32)/10; // Ensure hi >= 0.9
     ^~~~~
In file included from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:11:0:
/home/gvaillan/local/src/arrayfire/include/af/array.h:27:17: note: candidates are: class af::array
     class AFAPI array {
                 ^~~~~
In file included from /usr/include/c++/6/tuple:39:0,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-port.h:708,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-internal.h:40,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/gtest.h:58,
                 from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:10:
/usr/include/c++/6/array:90:12: note:                 template<class _Tp, long unsigned int _Nm> struct std::array
     struct array
            ^~~~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:71:5: error: reference to ‘array’ is ambiguous
     array out = clamp(in, lo, hi);
     ^~~~~
In file included from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:11:0:
/home/gvaillan/local/src/arrayfire/include/af/array.h:27:17: note: candidates are: class af::array
     class AFAPI array {
                 ^~~~~
In file included from /usr/include/c++/6/tuple:39:0,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-port.h:708,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-internal.h:40,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/gtest.h:58,
                 from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:10:
/usr/include/c++/6/array:90:12: note:                 template<class _Tp, long unsigned int _Nm> struct std::array
     struct array
            ^~~~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:73:5: error: ‘out’ was not declared in this scope
     out.host(&hout[0]);
     ^~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:74:5: error: ‘in’ was not declared in this scope
     in.host(&hin[0]);
     ^~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:75:5: error: ‘hi’ was not declared in this scope
     hi.host(&hhi[0]);
     ^~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp: In member function ‘virtual void ClampTests_FloatScalarScalar_Test::TestBody()’:
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:86:5: error: reference to ‘array’ is ambiguous
     array in = af::randu(num, f32);
     ^~~~~
In file included from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:11:0:
/home/gvaillan/local/src/arrayfire/include/af/array.h:27:17: note: candidates are: class af::array
     class AFAPI array {
                 ^~~~~
In file included from /usr/include/c++/6/tuple:39:0,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-port.h:708,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-internal.h:40,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/gtest.h:58,
                 from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:10:
/usr/include/c++/6/array:90:12: note:                 template<class _Tp, long unsigned int _Nm> struct std::array
     struct array
            ^~~~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:91:5: error: reference to ‘array’ is ambiguous
     array out = clamp(in, lo, hi);
     ^~~~~
In file included from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:11:0:
/home/gvaillan/local/src/arrayfire/include/af/array.h:27:17: note: candidates are: class af::array
     class AFAPI array {
                 ^~~~~
In file included from /usr/include/c++/6/tuple:39:0,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-port.h:708,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/internal/gtest-internal.h:40,
                 from /home/gvaillan/local/src/arrayfire/test/../test/gtest/include/gtest/gtest.h:58,
                 from /home/gvaillan/local/src/arrayfire/test/clamp.cpp:10:
/usr/include/c++/6/array:90:12: note:                 template<class _Tp, long unsigned int _Nm> struct std::array
     struct array
            ^~~~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:93:5: error: ‘out’ was not declared in this scope
     out.host(&hout[0]);
     ^~~
/home/gvaillan/local/src/arrayfire/test/clamp.cpp:94:5: error: ‘in’ was not declared in this scope
     in.host(&hin[0]);
     ^~

```

**Comment by pavanky** [comment]
@ghisvail my bad. I put both `using namespace std` and `using namepsace af` in the test.

I wonder what options are different in debian testing that it is catching this that other distros are not.

For reference, we use Debian 8 for building PRs, centos 6.x for building branches, I develop on archlinux, others at arrayfire use ubuntu 16.04.

**Comment by pavanky** [comment]
Oh we are not even including `<array>`, so it is weird that there is a conflict. It could potentially be an issue because of some system header automatically pulling it in.

Anyway I am going to fix this in #1584

**Comment by ghisvail** [comment]
> I wonder what options are different in debian testing

The default compiler. Debian 8 has gcc-4.9 and builds in c++03 by default, Ubuntu 16.04 has gcc-5.3.1 (not sure what the default is, probably c++11), Debian testing and next Ubuntu both have gcc-6.1.1 with c++14 as default.

**Comment by pavanky** [comment]
Archlinux has 6.1.1 (which is what I develop on). It looks like the difference is in the gtest being compiled.
