### ISSUE TITLE
JIT Issue on Tegra TX Devices is back ?

### ISSUE THREAD

**Issue by HoneyPatouceul** [arrayfire/arrayfire#2028]
Looks similar to https://github.com/arrayfire/arrayfire/issues/1910, but it may have a different cause.

I have upgraded my TX2 with R28.2 and cuda9.0 and built arrayfire 3.6.0.
The code that was working with R28.1 and cuda8.0 (after bug #1910 had been fixed) no longer works and fails with:
```
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):

In function void cuda::evalNodes(std::vector<cuda::Param<T> >&, std::vector<cuda::JIT::Node*>) [with T = float2]
In file src/backend/cuda/jit.cpp:469
CU Error (701)

In function af::array af::fft2Norm(const af::array&, double, dim_t, dim_t)
In file src/api/cpp/fft.cpp:27
Aborted (core dumped)
```

The failure happens on 6th iteration of code after 5 successful iterations.

**Comment by umar456** [comment]
@pavanky Looks like the kernel was too large.

```
CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES = 701
    This indicates that a launch did not occur because it did not have appropriate resources. This error usually indicates that the user has attempted to pass too many arguments to the device kernel, or the kernel launch specifies too many threads for the kernel's register count. Passing arguments of the wrong size (i.e. a 64-bit pointer when a 32-bit int is expected) is equivalent to passing too many arguments and can also result in this error. 
```

I wonder if there is a programmatic way to figure out the limitation of the devices.

**Comment by pavanky** [comment]
@HoneyPatouceul Can you add `af::eval(output)` (or whatever it is called) at the end of the iteration ?

If you have more than one output (and if they are the same shape) add `af::eval(output1, output2, output3)` at the end of the loop.

**Comment by HoneyPatouceul** [comment]
**@pavanky**  I had already done that. Adding an intermediate eval in the loop before a call to a function solved it...but now my code failed elsewhere after many iterations (runs about 20 minutes before error, so it's not easy to track) :


Is there a way to limit lazy evaluation ?  The thing is that this code was working fine and fast with TX1 with the last 32bits version (L4T R23.2) and cuda7.0.
When moved to 64 bits and cuda8.0, it started failing with memory outage, so I've had to add some deviceGC(). When upgraded to R28.1 and cuda8.0.61, I've had to add many eval() and some sync().
Now with R28.2 and cuda9.0, I have to add more eval()...  
```
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function void cuda::evalNodes(std::vector<cuda::Param<T> >&, std::vector<cuda::JIT::Node*>) [with T = float]
In file src/backend/cuda/jit.cpp:469
CU Error (701)


In function void af::array::host(void*) const
In file src/api/cpp/array.cpp:254
Aborted (core dumped)

```
Are there some arrayfire coding guidelines for this available on the web ?
Furthermore, my app is performing about 30 iterations for processing one image. Since cuda8, the 30 iterations for the first image are slow, and processing the second image is 4 times faster. May it be related to lazy eval ?

Thanks for your help.

**Comment by pavanky** [comment]
@HoneyPatouceul you can try playing aroung with `AF_CUDA_MAX_JIT_LEN` environment variable. More here: http://arrayfire.org/docs/configuring_environment.htm#af_cuda_max_jit_len

Btw if something was working on an older version of the toolkit and is broken now, it is a regression from NVIDIA's side. There's not much that can be done from arrayfire's side.

**Comment by HoneyPatouceul** [comment]
**@pavanky**

Thanks for the info. Indeed, setting AF_CUDA_MAX_JIT_LEN to 13 or less allows my app to run.
I don't see much difference from 1 or 2 to 13.
Furthermore, maybe off topic, but in the link you mentioned, I feel a bit confused about :  
AF_MEM_DEBUG

```
When AF_MEM_DEBUG is set to 1 (or anything not equal to 0), the caching mechanism in the memory manager is disabled. The device buffers are allocated using native functions as needed and freed when going out of scope.

When the environment variable is not set, it is treated to be non zero.
```
So the mem debug is enabled by default ?

**Comment by HoneyPatouceul** [comment]
[https://devtalk.nvidia.com/default/topic/1027893/arrayfire-lib-performance-among-l4t-cuda-new-versions/](url)

**Comment by pavanky** [comment]
@HoneyPatouceul I think the documentation is incorrect. The default is set to zero.

Do you want to send in a patch to fix the docs ? The location of the file is: docs/pages/configuring_arrayfire_environment.md

**Comment by pavanky** [comment]
> http://devtalk.nvidia.com/default/topic/1027893/arrayfire-lib-performance-among-l4t-cuda-new-versions/

If you are building arrayfire from source, you can print `jit_ker` immediately after this line: https://github.com/arrayfire/arrayfire/blob/master/src/backend/cuda/jit.cpp#L359

There will be multiple kernels that are printed. You can just send them the last kernel that is failing.

**Comment by HoneyPatouceul** [comment]
> @HoneyPatouceul I think the documentation is incorrect. The default is set to zero.

> Do you want to send in a patch to fix the docs ? The location of the file is: docs/pages/configuring_arrayfire_environment.md

I think it's done. Let me know if you don't see my patch or if it's not correct.

**Comment by HoneyPatouceul** [comment]
Running the tests shows 3 tests failing (blas_cuda, canny_cuda that leads to gpu memory fault, and jit_cuda).
For jit_cuda, the unit test failing is JIT.ISSUE_1646 that throws similar exception as reported:
```
[ RUN      ] JIT.ISSUE_1646
unknown file: Failure
C++ exception with description "ArrayFire Exception (Internal error:998):
In function void cuda::evalNodes(std::vector<cuda::Param<T> >&, std::vector<cuda::JIT::Node*>) [with T = float]
In file src/backend/cuda/jit.cpp:471
CU Error (701)


In function af::array& af::array::operator+=(const af::array&)
In file src/api/cpp/array.cpp:814" thrown in the test body.
[  FAILED  ] JIT.ISSUE_1646 (760 ms)
```

It fails when setting AF_CUDA_MAX_JIT_LEN to 19 or more, and succeeds with 18 or less.

**Comment by HoneyPatouceul** [comment]
Confirmed the same on TX1 running L4T R28.1. Same limit 18 for AF_CUDA_MAX_JIT_LEN for passing test JIT.ISSUE_1646. Reported to NVIDIA in previously mentioned topic, waiting for their advices.

**Comment by pavanky** [comment]
Hmm the generated kernel looks incorrect. @umar456 can you look at the code and see if there is any overflow issues on arrayfire's end ?

**Comment by pavanky** [comment]
Nevermind. I misread the kernel code. @HoneyPatouceul Thanks for reporting it to nvidia :)

**Comment by HoneyPatouceul** [comment]
Seems that the release build is working fine :-), at least on JIT.ISSUE_1646. 
But Debug build (or default, having CMAKE_BUILD_TYPE undefined) leads to this error. 
Do you see anything that might explain this ?

**Comment by pavanky** [comment]
I am not entirely sure.. 

@umar456 any thoughts?

**Comment by umar456** [comment]
Perhaps this is the issue: 
https://github.com/arrayfire/arrayfire/blob/master/src/backend/cuda/jit.cpp#L285

@HoneyPatouceul Can you delete those lines and check if you run into this issue?

**Comment by pavanky** [comment]
@umar456 wasn't this added recently ?

@HoneyPatouceul is the bug reproducible on older versions of arrayfire?

**Comment by HoneyPatouceul** [comment]
@umar456   Indeed, commenting those lines solves the issue.

**Comment by HoneyPatouceul** [comment]
> @HoneyPatouceul is the bug reproducible on older versions of arrayfire?
The debug build with 3.4.2 passes the test.
The debug build with 3.5.1 fails the test.

**Comment by pavanky** [comment]
@HoneyPatouceul Thanks for double checking.

@umar456 shouldn't `NDEBUG` be set by default ?

**Comment by HoneyPatouceul** [comment]
> shouldn't NDEBUG be set by default ?
This would allow a default build to pass.
But how to do with debug builds ? Should be AF_CUDA_MAX_JIT_LEN be set to a lower value for debug builds, or is there a way to solve the "--device-debug" issue ?

**Comment by pavanky** [comment]
@HoneyPatouceul The bug still exists on nvidia's side. It is only showing up with the specified flags. Those flags are not necessarily needed for JIT to work. @umar456 can you remove them (or atleast disable them for tegra devices) ?

**Comment by umar456** [comment]
Yeah, I can take care of that in a couple of days.

**Comment by HoneyPatouceul** [comment]
>     shouldn't NDEBUG be set by default ?
> 
> This would allow a default build to pass.

I may have been simplistic saying that.
Having NDEBUG defined by default may make debug builds more complicated, unless moving to DEBUG definition instead with many potential side effects.
NVIDIA knows about this, so I expect they can reproduce and advice or fix in a future release.

**Comment by HoneyPatouceul** [comment]
Got this answer from nvidia: 
[](https://devtalk.nvidia.com/default/topic/1027893/arrayfire-lib-performance-among-l4t-cuda-new-versions/?offset=25#5236551)
Does this make sense to you ?

**Comment by pavanky** [comment]
@HoneyPatouceul 
I don't want to create an account (or go digging for my old login credentials) to reply on that thread. The out of resources error could potentially come from multiple places. 

I highly doubt this is because of threads. The number of threads are fixed for our JIT kernels (256 or 1024). 

In this case I assume it is probably coming from using too much constant memory (which is used to store the kernel parameters).  Considering that it works in release mode but not in debug mode, I'd assume they are putting additional stuff in constant memory during debug mode which is reducing the amount of available space for kernel parameters.
