### ISSUE TITLE
Building on Ubuntu 14.04

### ISSUE THREAD

**Issue by paulheideman** [arrayfire/arrayfire#919]
Hi,

I get this problem when build on Ubuntu 14.04, am I missing a dependency maybe?

```
<snip>
[ 70%] Building CXX object test/CMakeFiles/approx1_cpu.dir/approx1.cpp.o
Linking CXX executable approx1_cpu
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XcursorImageLoadCursor'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XineramaQueryExtension'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XF86VidModeQueryExtension'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRGetCrtcInfo'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRGetCrtcGamma'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XineramaQueryScreens'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XineramaIsActive'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRSelectInput'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XF86VidModeGetGammaRampSize'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XcursorImageDestroy'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XISelectEvents'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRGetOutputPrimary'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XIQueryVersion'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRGetScreenResources'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XF86VidModeGetGammaRamp'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRGetOutputInfo'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRAllocGamma'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRQueryExtension'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRUpdateConfiguration'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRGetScreenResourcesCurrent'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRSetCrtcConfig'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRGetCrtcGammaSize'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XF86VidModeSetGammaRamp'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRSetCrtcGamma'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRFreeOutputInfo'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XcursorImageCreate'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRQueryVersion'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRFreeScreenResources'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRFreeGamma'
/home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so: undefined reference to `XRRFreeCrtcInfo'
collect2: error: ld returned 1 exit status
make[2]: *** [test/approx1_cpu] Error 1
make[1]: *** [test/CMakeFiles/approx1_cpu.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by 9prady9** [comment]
@paulheideman Do you have X libs installed ? Forge's upstream libraries use X libs, and this should be available on Ubuntu by default right ?

**Comment by paulheideman** [comment]
I have these packages installed:
```
xorg-dev/trusty-updates,now 1:7.7+1ubuntu8.1 all [installed]
  X.Org X Window System development libraries

xserver-xorg-dev/trusty-updates,trusty-security,now 2:1.15.1-0ubuntu2.7 amd64 [installed]
  Xorg X server - development files

libx11-dev/trusty,now 2:1.6.2-1ubuntu2 amd64 [installed]
  X11 client-side library (development headers)
```
Are they the ones you're asking about?

**Comment by shehzan10** [comment]
Can you check whether you have the following packages:
* libxinerama-dev
* libxrandr-dev
* libxi-dev
* libxcursor-dev

These are a subset of packages that should be installed when xorg-dev is installed.

**Comment by paulheideman** [comment]
Yup, got them.

**Comment by shehzan10** [comment]
Ok. The for an unknown reason libforge is not linking correctly with these.
Can you do `ldd /home/paul/dev/arrayfire/build/third_party/forge/src/forge-ext-build/src/libforge.so` and paste the output.

**Comment by paulheideman** [comment]
```
	linux-vdso.so.1 =>  (0x00007ffdc694e000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fedf4846000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fedf4517000)
	libGLEWmx.so.1.10 => /usr/lib/x86_64-linux-gnu/libGLEWmx.so.1.10 (0x00007fedf4299000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fedf3f95000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fedf3c8f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fedf3a79000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fedf36b4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fedf4d62000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fedf3411000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fedf31e7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fedf2fc9000)
	libnvidia-tls.so.352.21 => /usr/lib/x86_64-linux-gnu/tls/libnvidia-tls.so.352.21 (0x00007fedf2dc6000)
	libnvidia-glcore.so.352.21 => /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.352.21 (0x00007fedf0335000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fedf0000000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fedefdee000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fedefbea000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fedef9d1000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fedef7ab000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fedef58c000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fedef388000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fedef182000)
```

**Comment by shehzan10** [comment]
That's weird. The third party build of forge should use glfw3.
And GLFW3 is not one of the dependencies for forge in the log you showed here.

I thought to ask whether you have glfw3 installed, but that is not the case because cmake itself would fail. But just out of curiosity, did you install GLFW 2 or GLFW 3?

**Comment by paulheideman** [comment]
I built it from source from your link, so I guess 3, but maybe I missed a step.

**Comment by paulheideman** [comment]
Here is the install manifest if that helps:
/usr/local/include/GLFW/glfw3.h
/usr/local/include/GLFW/glfw3native.h
/usr/local/lib/cmake/glfw/glfw3Config.cmake
/usr/local/lib/cmake/glfw/glfw3ConfigVersion.cmake
/usr/local/lib/cmake/glfw/glfwTargets.cmake
/usr/local/lib/cmake/glfw/glfwTargets-noconfig.cmake
/usr/local/lib/pkgconfig/glfw3.pc
/usr/local/lib/libglfw3.a

**Comment by shehzan10** [comment]
Ah got it.
You built only the static lib. That's why it doesn't show up on the ldd.
When you use static lib, you have to link all the X libraries explicitly to the executables, and hence the undefined references.

On the [GLFW-for-ArrayFire](https://github.com/arrayfire/arrayfire/wiki/GLFW-for-ArrayFire) page we have `cmake .. -DBUILD_SHARED_LIBS=ON`. Ensure the option is set.

**Comment by paulheideman** [comment]
That works! Thanks!
