### ISSUE TITLE
[Build] Fails to build with SPDLog 1.14.0

### ISSUE THREAD

**Issue by SMillerDev** [arrayfire/arrayfire#3549]
```
[ 22%] Linking CXX executable basic_unified
  cd /tmp/arrayfire-20240513-15875-9klqee/arrayfire-full-v3.9.0/build/examples/unified && /home/linuxbrew/.linuxbrew/Cellar/cmake/3.29.3/bin/cmake -E cmake_link_script CMakeFiles/basic_unified.dir/link.txt --verbose=1
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-11 -include climits -O3 -DNDEBUG CMakeFiles/basic_unified.dir/basic.cpp.o -o basic_unified  -Wl,-rpath,/tmp/arrayfire-20240513-15875-9klqee/arrayfire-full-v3.9.0/build/src/api/unified ../../src/api/unified/libaf.so.3.9.0
  /home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: ../../src/api/unified/libaf.so.3.9.0: undefined reference to `spdlog::get(char const*)'
  collect2: error: ld returned 1 exit status
  make[2]: *** [examples/unified/CMakeFiles/basic_unified.dir/build.make:101: examples/unified/basic_unified] Error 1
```

Description
===========

When building arrayfire in https://github.com/Homebrew/homebrew-core/pull/170154 we ran into this issue.
It occurs on macOS and Linux

Error Log
---------

```

```

Build Environment
-----------------
Compiler version: 
Operating system: 
Build environment: 
CMake variables:

**Comment by edwinsolisf** [comment]
It seems there has been a [fix upstream](https://github.com/Homebrew/homebrew-core/pull/173484). Try updating the spdlog package. Closing this issue, reopen it if the problem still remains.
