### ISSUE TITLE
[Build] Ubuntu 16 CUDA

### ISSUE THREAD

**Issue by henry090** [arrayfire/arrayfire#2951]
Description
===========
Hi. Could you look at the error and tell what I am doing wrong?

Error Log
---------

```
turgut@turgut:~$ cd ~/Documents/arrayfire
turgut@turgut:~/Documents/arrayfire$ mkdir build && cd build
turgut@turgut:~/Documents/arrayfire/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_CUDA=ON -DAF_BUILD_CPU=OFF -DAF_BUILD_OPENCL=OFF
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Could NOT find OpenCL (missing:  OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "10.1", minimum required is "9.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found cuDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so.7 (found suitable version "7.6", minimum required is "4.0") 
-- Could NOT find OpenCL (missing:  OpenCL_LIBRARY OpenCL_INCLUDE_DIR) (Required is at least version "1.2")
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found FreeImage: /usr/include  
-- Checking for module 'fftw3'
--   Found fftw3, version 3.3.4
-- Found FFTW: /usr/include  
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [Accelerate]
-- Checking for [vecLib]
-- Checking for [cblas - atlas]
-- Includes found
-- Looking for cblas_dgemm
-- Looking for cblas_dgemm - found
-- CBLAS Symbols FOUND
-- CBLAS library found
-- Found LAPACKE: /usr/lib/liblapacke.so;/usr/lib/openblas-base/liblapack.so;/usr/lib/openblas-base/libblas.so  
-- Found LAPACK: /usr/include  
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- Check size of int
-- Check size of int - done
-- MKL: Thread Layer(Intel OpenMP) Interface(4-byte Integer)
-- Could NOT find MKL: Source the compilervars.sh or mklvars.sh scripts included with your installation of MKL. This script searches for the libraries in MKLROOT, LIBRARY_PATHS(Linux), and LIB(Windows) environment variables (missing:  MKL_INCLUDE_DIR MKL_Core_LINK_LIBRARY MKL_Interface_LINK_LIBRARY MKL_ThreadLayer_LINK_LIBRARY) 
-- Could NOT find MKL: Source the compilervars.sh or mklvars.sh scripts included with your installation of MKL. This script searches for the libraries in MKLROOT, LIBRARY_PATHS(Linux), and LIB(Windows) environment variables (missing:  MKL_INCLUDE_DIR MKL_Core_STATIC_LINK_LIBRARY MKL_Interface_STATIC_LINK_LIBRARY MKL_ThreadLayer_STATIC_LINK_LIBRARY) 
-- Boost version: 1.70.0
-- CUDA_architecture_build_targets: 7.5 
-- Performing Test group_flags
-- Performing Test group_flags - Success
-- Performing Test has_ignored_attributes_flag
-- Performing Test has_ignored_attributes_flag - Success
-- Performing Test has_all_warnings_flag
-- Performing Test has_all_warnings_flag - Success
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Performing Test pthread_flag
-- Performing Test pthread_flag - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/turgut/Documents/arrayfire/build
turgut@turgut:~/Documents/arrayfire/build$ make install
Scanning dependencies of target bin2cpp
[  0%] Building CXX object CMakeFiles/bin2cpp.dir/CMakeModules/bin2cpp.cpp.o
[  0%] Linking CXX executable bin2cpp
[  0%] Built target bin2cpp
Scanning dependencies of target cuda_nvrtc_kernel_headers_bin_target
[  1%] Compiling /usr/local/cuda/include/cuda_fp16.h to C++ source
[  1%] Compiling /usr/local/cuda/include/cuda_fp16.hpp to C++ source
[  1%] Compiling /usr/local/cuda/include/cuComplex.h to C++ source
[  1%] Compiling /usr/local/cuda/include/math_constants.h to C++ source
[  1%] Compiling /home/turgut/Documents/arrayfire/src/api/c/optypes.hpp to C++ source
[  1%] Compiling /home/turgut/Documents/arrayfire/include/af/defines.h to C++ source
[  1%] Compiling /home/turgut/Documents/arrayfire/include/af/traits.hpp to C++ source
[  1%] Compiling /home/turgut/Documents/arrayfire/build/include/af/version.h to C++ source
[  1%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/Param.hpp to C++ source
[  1%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/assign_kernel_param.hpp to C++ source
[  1%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/backend.hpp to C++ source
[  1%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/dims_param.hpp to C++ source
[  2%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/interp.hpp to C++ source
[  2%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/shared.hpp to C++ source
[  2%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/math.hpp to C++ source
[  2%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/minmax_op.hpp to C++ source
[  2%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/utility.hpp to C++ source
[  2%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/types.hpp to C++ source
[  2%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/../common/Binary.hpp to C++ source
[  2%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/../common/Transform.hpp to C++ source
[  2%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/../common/half.hpp to C++ source
[  2%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/../common/internal_enums.hpp to C++ source
[  2%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/../common/kernel_type.hpp to C++ source
[  2%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/anisotropic_diffusion.cuh to C++ source
[  3%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/approx1.cuh to C++ source
[  3%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/approx2.cuh to C++ source
[  3%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/assign.cuh to C++ source
[  3%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/bilateral.cuh to C++ source
[  3%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/canny.cuh to C++ source
[  3%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/convolve1.cuh to C++ source
[  3%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/convolve2.cuh to C++ source
[  3%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/convolve3.cuh to C++ source
[  3%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/convolve_separable.cuh to C++ source
[  3%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/copy.cuh to C++ source
[  3%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/diagonal.cuh to C++ source
[  3%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/diff.cuh to C++ source
[  3%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/exampleFunction.cuh to C++ source
[  4%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/fftconvolve.cuh to C++ source
[  4%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/flood_fill.cuh to C++ source
[  4%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/gradient.cuh to C++ source
[  4%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/histogram.cuh to C++ source
[  4%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/hsv_rgb.cuh to C++ source
[  4%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/identity.cuh to C++ source
[  4%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/iir.cuh to C++ source
[  4%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/index.cuh to C++ source
[  4%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/iota.cuh to C++ source
[  4%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/ireduce.cuh to C++ source
[  4%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/join.cuh to C++ source
[  4%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/lookup.cuh to C++ source
[  5%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/lu_split.cuh to C++ source
[  5%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/match_template.cuh to C++ source
[  5%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/meanshift.cuh to C++ source
[  5%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/medfilt.cuh to C++ source
[  5%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/memcopy.cuh to C++ source
[  5%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/moments.cuh to C++ source
[  5%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/morph.cuh to C++ source
[  5%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/pad_array_borders.cuh to C++ source
[  5%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/range.cuh to C++ source
[  5%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/resize.cuh to C++ source
[  5%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/reorder.cuh to C++ source
[  5%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/rotate.cuh to C++ source
[  5%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/select.cuh to C++ source
[  6%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/scan_dim.cuh to C++ source
[  6%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/scan_dim_by_key.cuh to C++ source
[  6%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/scan_first.cuh to C++ source
[  6%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/scan_first_by_key.cuh to C++ source
[  6%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/sobel.cuh to C++ source
[  6%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/sparse.cuh to C++ source
[  6%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/sparse_arith.cuh to C++ source
[  6%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/susan.cuh to C++ source
[  6%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/tile.cuh to C++ source
[  6%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/transform.cuh to C++ source
[  6%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/transpose.cuh to C++ source
[  6%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/transpose_inplace.cuh to C++ source
[  7%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/triangle.cuh to C++ source
[  7%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/unwrap.cuh to C++ source
[  7%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/where.cuh to C++ source
[  7%] Compiling /home/turgut/Documents/arrayfire/src/backend/cuda/kernel/wrap.cuh to C++ source
[  7%] Built target cuda_nvrtc_kernel_headers_bin_target
[  8%] Building NVCC (Device) object src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir/af_cuda_static_cuda_library_generated_solve.cu.o
[  8%] Building NVCC (Device) object src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir/af_cuda_static_cuda_library_generated_blas.cu.o
/home/turgut/Documents/arrayfire/src/backend/common/jit/NaryNode.hpp(43): error: static assertion failed with "NaryNode is not move assignable"

/home/turgut/Documents/arrayfire/src/backend/common/jit/UnaryNode.hpp(19): error: static assertion failed with "UnaryNode is not move assignable"

2 errors detected in the compilation of "/tmp/tmpxft_00003bfe_00000000-6_blas.cpp1.ii".
CMake Error at af_cuda_static_cuda_library_generated_blas.cu.o.cmake:266 (message):
  Error generating file
  /home/turgut/Documents/arrayfire/build/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_blas.cu.o


src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir/build.make:63: recipe for target 'src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir/af_cuda_static_cuda_library_generated_blas.cu.o' failed
make[2]: *** [src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir/af_cuda_static_cuda_library_generated_blas.cu.o] Error 1
CMakeFiles/Makefile2:1204: recipe for target 'src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir/all' failed
make[1]: *** [src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
turgut@turgut:~/Documents/arrayfire/build$ 

```

Build Environment
-----------------
```gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609```

**Comment by 9prady9** [comment]
@henry090 Thank you for reporting it. It is because of the compiler version of gcc you have on Ubuntu 16.04, 5.4.

NaryNode is not move assignable because it has std::string. That is the case with gcc 5.4. I have verified this using godblot, removing `std::string` compiles fine. The code works fine with GCC 5.5 though.

@umar456 How do you think we should proceed ?

**Comment by umar456** [comment]
I have a fix for this. I should have a fix for this sometime today.
